### ISSUE TITLE
Huge names are bad :)

### ISSUE THREAD

**Issue by fserb** [andyli/hxColorToolkit#1]
I love the work you did on this library. Everything I need color-wise this library does well.

The only major downside of this library (which makes me want to use other stuff or copy this to my own library) is the name. First, every single Library in lib.haxe is a "Toolkit".

Second, I think importing "*" is a bad thing in general and having to type things like "hxColorToolkit.ColorToolkit.toHSL(0x123456)" or "new hxColorToolkit.spaces.HSL()" doesn't really make anyone life's better.

It's such a clean, useful and nice API. That is attached to a clumsy, big, unfriendly name. 
Just call it "Color": "Color.toHSL()" "Color.space.HSL()" etc. :)

hugs and <3

**Comment by ubald** [comment]
I've seen worse ;)
But it's not really an issue when the IDE auto-completes and/or auto imports the classes.

**Comment by andyli** [comment]
Thanks for the comments!

Well, the lib name is merely putting "hx" in front of "colortoolkit", which this lib was originally ported from.

You can import ColorToolkit as `import hxColorToolkit.ColorToolkit as Clr;` (use `in` instead of `as` if you're using 3.1.3).
For the color space classes, they are really meant to be import in the way `import hxColorToolkit.spaces.*`... what is the problem of using import wildcard?

**Comment by fserb** [comment]
Well, with wildcard import you never know what you are bringing to the namespace, right? It can cause weird collisions.

But more important, you don't know where things are coming from when you read code.
Imagine a code with a bunch of `import bla.*` and you call `SuperDuper()` and now it's good luck for you trying to find out which library provides `SuperDuper`, because it's not explicitly imported.

What I've been doing so far is compiling everything with `--remap "color:hxColorToolkit"` which solves a bit of the problem. I still have to do `color.ColorToolkit.<bla>`, but it's much less characters on the screen. But it's cheat-y, and it may lead to people being confused when reading code.

I know it's just a silly rant (and thanks for answering, btw). My point is that clear and less verbose is usually better. And I feel `hxColorToolkit.ColorToolkit` (it has `Toolkit` twice!) is a tad too much. :)

**Comment by andyli** [comment]
It reminds me the famous quote, "There are only two hard things in Computer Science: cache invalidation and naming things.". :)

In fact, I can see both of us want to reduce ambiguity and want things to be short and nice, it is just we are using different approaches:
You want to use fully qualify names (less ambiguous), and have shorter names such that they look nice  (short and nice).
I want to use longer names (less ambiguous), and import them to remove the need of typing the packages (short and nice).

Since the two approaches are on a par with each other, I would favor to stay as is, such that no current code will be broken by renaming.
